# Generated by Django 3.0.2 on 2020-01-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_articolo', models.CharField(max_length=90)),
                ('descrizione_articolo', models.CharField(blank=True, max_length=90, null=True)),
                ('immagine_articolo', models.ImageField(blank=True, null=True, upload_to='')),
                ('contenuto', models.TextField()),
                ('data_di_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
    ]
