# Generated by Django 3.0.2 on 2020-01-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='autore',
        ),
    ]
